# Sales Records Analysis
### Author: Natalia Miranda
### Exercise 2.E Using functions for analyzing data
This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argument.

In [1]:
# create sales dataset
# each tuple contains: (product, region, amount)
sales_data = [
('Laptop', 'East', 1200.00),
('Phone', 'West', 850.00),
('Tablet', 'East', 400.00),
('Monitor', 'South', 650.00),
('Keyboard', 'West', 75.00),
('Laptop', 'South', 1150.00),
('Phone', 'East', 900.00),
('Tablet', 'West', 425.00),
('Monitor', 'East', 680.00),
('Keyboard', 'South', 80.00),
('Laptop', 'West', 1300.00),
('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region

In [2]:
# function to calculate total sales for a specific region

def region_total(data, region):
    #sum all ammounts where region matches
    return sum(
        amt for _, r, amt in data if r == region
    )

In [5]:
# test totals 
print(region_total(sales_data, 'East'))
print(region_total(sales_data, 'West'))
print(region_total(sales_data, 'South'))

3180.0
3470.0
1880.0


## Lab 2. Count of sales by region

In [6]:
# function to count records for a specific region
def region_count(data, region):
    # add 1 for every matching record
    return sum(
        1 for _, r, amt in data if r == region
    )

In [7]:
# Test counts 
print(region_count(sales_data, 'East'))
print(region_count(sales_data, 'West'))
print(region_count(sales_data, 'South'))


4
5
3


## Lab 3. Average sale amount by region

In [9]:
# function to calculate average sales for a specific region
def region_average(data, region):
    #get total sales
    total = region_total(data, region)
    #get count for records
    count = region_count(data, region)
    #prevent division by zero
    if count == 0:
        return 0

    # Calculate average 
    return total / count

In [10]:
# Test averages 
print(region_average(sales_data, 'East'))
print(region_average(sales_data, 'West'))
print(region_average(sales_data, 'South'))

# Test region with no records
print(region_average(sales_data, 'North'))


795.0
694.0
626.6666666666666
0


## Lab 4. Filter by sale amount

In [12]:
# function to return sales
# above a threshold
def sales_above(data, threshold):
    #create a list with remaining records
    return [
        record for record in data

        #record[2] = sale amount
        if record[2] > threshold
    ]

In [13]:
# store results 
high_sales = sales_above(sales_data, 500)
# print each record
for record in high_sales:
    print(record)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


In [14]:
# BONUS LAP 4
# Function to return sales below a threshold
def sales_below(data, threshold):
    return [
        record for record in data
        if record[2] < threshold
    ]

In [15]:
#store results
low_sales = sales_below(sales_data, 500)

#print each record 
for record in low_sales:
    print(record)

('Tablet', 'East', 400.0)
('Keyboard', 'West', 75.0)
('Tablet', 'West', 425.0)
('Keyboard', 'South', 80.0)


## Lab 5. Top and bottom sale

In [17]:
# function to find highest sale
def top_sale(data):
    #compare tuples using amount
    return max(data, key=lambda s: s[2])

# function to find lowest sale
def bottom_sale(data):
    #compare tuples using amount
    return min(data, key=lambda s: s[2])

In [18]:
# print highest sale
print(top_sale(sales_data))

# print lowest sale
print(bottom_sale(sales_data))

('Laptop', 'West', 1300.0)
('Keyboard', 'West', 75.0)


The top sale was a Laptop in the West region for $1300.00.

The bottom sale was a Keyboard in the West region for $75.00.

## Lab 6. Apply a discount

In [20]:
# function to apply discount
def apply_discount(data, discount_pct):
    #use map() to update amounts
    discounted = map(
        lambda s: (
            s[0], # product
            s[1], # region
            s[2] * (1- discount_pct) #discounted amount
        ),
        data
    )

    #convert map object into list
    return list(discounted)

In [21]:
# Apply 15% discount 
discounted_sales = apply_discount(sales_data, 0.15) 

# print first 3 original records
print("Original records")
for record in sales_data[:3]:
    print(record)
print()

# print first 3 discounted records
print("Discounted Records")
for record in discounted_sales[:3]:
    print(record)

Original records
('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Tablet', 'East', 400.0)

Discounted Records
('Laptop', 'East', 1020.0)
('Phone', 'West', 722.5)
('Tablet', 'East', 340.0)


## Lab 7. Unique regions 

In [25]:
# function to get unique regions
def unique_regions(data):
    # extract regions and remove duplicates 
    return sorted(
        set(
            r for _, r, amt in data
        )
    )

In [26]:
# print unique regions
print(unique_regions(sales_data))

['East', 'South', 'West']


This function could be useful in a larger analysis program because it allows the program to automically identify all regions in a dataset without manually typing them.

This pattern can also be used for finding unique products, departments, employees, categories, or customers in datasets. It helps make programs more dynamic and reusable.

## Lab 8. Region Summary

In [28]:
# function to display region summary:
def region_summary(data, region):
    # get total sales
    total = region_total(data, region)
    # get count
    count = region_count(data, region)
    # get average 
    average = region_average(data, region)

    # narrow data to selected region
    region_data = [
        record for record in data
        if record[1] == region
    ]
    # Get top sale for that region
    top = top_sale(region_data)

    # Print formatted report
    print(f"==={region} Region ===")
    print(f"Records: {count}")
    print(f"Total Sales: ${format(total, '.2f')}")
    print(f"Average Sale: ${format(average, '.2f')}")
    print(f"Top Sale: {top[0]} - ${format(top[2], '.2f')}")
    

In [29]:
# test East Region
region_summary(sales_data, 'East')

===East Region ===
Records: 4
Total Sales: $3180.00
Average Sale: $795.00
Top Sale: Laptop - $1200.00


## Lab 9. Full summary

In [30]:
# loop through all unique regions
for region in unique_regions(sales_data):
    # print summary for each region 
    region_summary(sales_data, region)

    print()

===East Region ===
Records: 4
Total Sales: $3180.00
Average Sale: $795.00
Top Sale: Laptop - $1200.00

===South Region ===
Records: 3
Total Sales: $1880.00
Average Sale: $626.67
Top Sale: Laptop - $1150.00

===West Region ===
Records: 5
Total Sales: $3470.00
Average Sale: $694.00
Top Sale: Laptop - $1300.00



## Final Summary
In this exercise, I learned how to analyzed datasets using Python functions, generator expressions, list comprehensions, lambda functions, map(), max(),
min(), sets, and loops. I also learned how to create reusable functions that work together to calculate totals, averages , counts, filtering, discounts, and
summaries for sales data.
This exercise helped me better understand how data analysts can organize and analyze information using Python.